### ISSUE TITLE
Properties are ignored if not set at construction

### ISSUE THREAD

**Issue by ryascl** [type-route/type-route#17]
If a nullable prop is not set when controller is constructed, the prop does not recognize 'set' operations later. 
Workaround: If the prop is assigned value `undefined` in constructor, the prop works.

See commented line in constructor at:
https://codesandbox.io/s/react-use-controller-bug-report-nullable-prop-ttzop

**Comment by chris-kahn** [comment]
Did you open this issue in the wrong repo?

**Comment by ryascl** [comment]
My mistake! Closing.
