### ISSUE TITLE
Better type definitions for params

### ISSUE THREAD

**Issue by seivan** [type-route/type-route#33]
Related to https://github.com/type-route/type-route/issues/23

Could it be better to define params as types/interfaces, like react props? 
This would allow for scenarios where you could have `{currency: string, value: number} | null` meaning either are supplied or none is.

**Comment by bradenhs** [comment]
The new `params.path.ofType<T>()` way to create parameter definitions should resolve this. See https://github.com/type-route/type-route/pull/35 for more details.

**Comment by seivan** [comment]
It's a good start, but there's a lot of question marks, lets continue discussion in that PR since it's a work in progress.
