### ISSUE TITLE
featuring type-route in Docusaurus

### ISSUE THREAD

**Issue by nickbui729** [type-route/type-route#4]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) 

This has the benefits of giving projects recognition and also lets the community and new users reference the creative ways of using Docusaurus!

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by bradenhs** [comment]
This would be great! Unfortunately, the documentation site is still under construction. Once the docs have been filled out a little more I'd be happy for Docusaurus to feature type-route as a user. I'll let you know once things are ready.

**Comment by bradenhs** [comment]
Hi @nickbui729! I just published the Type Route documentation website. The url is [https://www.type-route.org](https://www.type-route.org) and here is a link to an svg version of the logo https://www.type-route.org/img/logo.svg. Let me know if you need anything else.

**Comment by bradenhs** [comment]
Thanks @nickbui729 for the idea. Just made a PR to add Type Route to Docusaurus users.
