### ISSUE TITLE
Very low website text contrast

### ISSUE THREAD

**Issue by elektronik2k5** [type-route/type-route#6]
Hello and thanks for working on this project! :)

I'm currently (and have been for a while) evaluating different routers out there. While I don't have any conclusions about yours (yet), I found it difficult to read the documentation. The contrast is very low and the font is so thin, that the combination makes it barely legible.

I'm no expert on a11y, so I ran the lighthouse a11y audit (in Chrome's DevTools) and it confirms:
> Contrast
These are opportunities to improve the legibility of your content.
Failing Elements
--
input#search_input_react.aa-input
a
span
span
section.copyright

**Comment by bradenhs** [comment]
Thanks for opening the issue. Definitely didn't think about accessibility when putting this together. For what its worth most (but not all) of the styles originate from the documentation tool Type Route uses: [Docusaurus](https://docusaurus.io/). All the same we can override those styles. I'd be happy to accept a PR on this if you're willing to take a stab :)

**Comment by bradenhs** [comment]
I adjusted some of the colors on the website to make the contrast better. I think everything passes lighthouse's color contrast check now except for the code examples (which would be harder to change). I'm going to go ahead and close this issue but feel free to reopen if there's something I missed.
