### ISSUE TITLE
Is there plan to provide <Router/> <Route/> <Navlink/> <Redirect/> to replace react-router?

### ISSUE THREAD

**Issue by lake2** [type-route/type-route#8]
I try to write the component by myself, but I don't know the best pratice. It will be nice if the package could provide code sample.

**Comment by bradenhs** [comment]
There are no exact equivalents of those components in Type Route. In theory it would be possible to write some component abstractions on top of the Type Route api to achieve this but in my (current) opinion providing React components would decrease flexibility without adding much value. 

If it helps here's a side by side example of how to write the same thing using Type Route and React Router: https://codesandbox.io/embed/laughing-rubin-bo8hn. This example doesn't cover how to do redirects using Type Route but there is a documentation page you can find for that here: https://www.type-route.org/docs/guides/redirects.

Does that help?

**Comment by bradenhs** [comment]
Going to close this for now. Feel free to reopen if the above explanation isn't clear enough :)

**Comment by aspirisen** [comment]
Hi, is there is a way to use `type-route` with react router, i can't get how to pass `path` to `Route` from react router which includes params?
